# Generated by Django 4.0.5 on 2022-06-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
