# Generated by Django 4.0.5 on 2022-07-03 15:09

from django.db import migrations, models
import django_google_maps.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_ordermodel_city_remove_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='houseno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
