# Generated by Django 4.0.5 on 2022-07-07 11:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_ordermodel_address_ordermodel_houseno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
