# Generated by Django 4.0.6 on 2022-07-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
