# Generated by Django 4.0.5 on 2022-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_remove_menuitem_category_remove_ordermodel_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
